import { ScaledSheet } from 'react-native-size-matters';

const styles = ScaledSheet.create({
  container:{
    paddingHorizontal: '80msr',
    flexDirection: 'row',
    gap:'3@s',
  },
  HorizontalScroll:{
    flexDirection: 'row',
  },
  selectedCard:{
    width: '80@s',
    height: '100@s',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#D40000',
    borderRadius: 5,
    backgroundColor: "#FFF",
    paddingTop: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.00,
    gap:'3@s',
  },
    euQueroContainer:{
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 5,
      position: 'relative',
      gap:'5@s',
    },
    euQueroItem:{
      flex: 1,
      width: '83@s',
      minWidth: 80,
      height: 120,
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: 'transparent',
      borderRadius: 5,
      backgroundColor: "#FFF",
      paddingTop: 10,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      gap: 3,
    },
    euQueroText: {
      fontSize: 12,
      fontWeight: "500",
      textAlign: 'center',
      paddingHorizontal: 3,
    },
    euQueroImage: {
      flex: 1,
      width: '100%',
      height: '100%',
      resizeMode: 'contain',
    },
    dropArea: {
      flex: 1,
      width: '100%',
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
    },
    lineReader: {
      width: "100%",
      height: '100@vs',
      flexDirection: "row",
      marginTop: "auto",
      marginBottom: "auto",
      position: "relative",

      backgroundColor: "#D9D9D9",

      alignItems: 'center',

    },
    faixaCentral:{
      width: '100%',
      height: '30@vs',
      backgroundColor: '#FFFF',
      position: 'absolute',
      alignSelf: 'center'
    },
    cardsContainer: {
      width: '100%',
      flexDirection: 'row',
      gap: 5,
      paddingHorizontal: '5@vs',
    },
    lineReaderLi: {
      width: '80@s',
      height: '100@s',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'transparent',
      borderRadius: 5,
      backgroundColor: "#FFF",
      paddingTop: 10,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      gap:'3@s',
    },
    lineText: {
      color: "white",
      fontSize: 14,
    },
    actionList: {
      
      flexDirection: "column",
      justifyContent: "space-between",
      position: "relative",
      gap: 10,
    },
    speakAction: {
      flex: 1,
      maxWidth: 100,
      backgroundColor: "#998BEB",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      borderRadius: 3,
      padding: 5,
      gap: 5,
  
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    deleteAction: {
      flex: 1,
      maxWidth: 100,
      height: "auto",
      backgroundColor: "#7C82BC",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 3,
      flexDirection: "row",
      padding: 5,
      gap: 5,
  
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    liText: {
      fontSize: 12,
      textAlign: 'center',
      paddingHorizontal: 3,
    },
    liImage: {
      flex: 1,
      width: '100%',
      height: '100%',
      resizeMode: 'contain',
    },
  });

  export default styles;